#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: e738c511eb94
#
Name     : SPIRV-Headers
Version  : 1.3.275.0
Release  : 13
URL      : https://github.com/KhronosGroup/SPIRV-Headers/archive/vulkan-sdk-1.3.275.0/SPIRV-Headers-1.3.275.0.tar.gz
Source0  : https://github.com/KhronosGroup/SPIRV-Headers/archive/vulkan-sdk-1.3.275.0/SPIRV-Headers-1.3.275.0.tar.gz
Summary  : Header files from the SPIR-V registry
Group    : Development/Tools
License  : MIT
Requires: SPIRV-Headers-data = %{version}-%{release}
Requires: SPIRV-Headers-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkg-config
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# SPIR-V Headers
This repository contains machine-readable files for the
[SPIR-V Registry](https://www.khronos.org/registry/spir-v/).
This includes:

%package data
Summary: data components for the SPIRV-Headers package.
Group: Data

%description data
data components for the SPIRV-Headers package.


%package dev
Summary: dev components for the SPIRV-Headers package.
Group: Development
Requires: SPIRV-Headers-data = %{version}-%{release}
Provides: SPIRV-Headers-devel = %{version}-%{release}
Requires: SPIRV-Headers = %{version}-%{release}

%description dev
dev components for the SPIRV-Headers package.


%package license
Summary: license components for the SPIRV-Headers package.
Group: Default

%description license
license components for the SPIRV-Headers package.


%prep
%setup -q -n SPIRV-Headers-vulkan-sdk-1.3.275.0
cd %{_builddir}/SPIRV-Headers-vulkan-sdk-1.3.275.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709080181
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709080181
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SPIRV-Headers
cp %{_builddir}/SPIRV-Headers-vulkan-sdk-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/SPIRV-Headers/9a84200f47e09abfbde1a6b25028460451b23d03 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/spirv/1.0/GLSL.std.450.h
/usr/include/spirv/1.0/OpenCL.std.h
/usr/include/spirv/1.0/extinst.glsl.std.450.grammar.json
/usr/include/spirv/1.0/extinst.opencl.std.100.grammar.json
/usr/include/spirv/1.0/spirv.core.grammar.json
/usr/include/spirv/1.0/spirv.cs
/usr/include/spirv/1.0/spirv.h
/usr/include/spirv/1.0/spirv.hpp
/usr/include/spirv/1.0/spirv.hpp11
/usr/include/spirv/1.0/spirv.json
/usr/include/spirv/1.0/spirv.lua
/usr/include/spirv/1.0/spirv.py
/usr/include/spirv/1.1/GLSL.std.450.h
/usr/include/spirv/1.1/OpenCL.std.h
/usr/include/spirv/1.1/extinst.glsl.std.450.grammar.json
/usr/include/spirv/1.1/extinst.opencl.std.100.grammar.json
/usr/include/spirv/1.1/spirv.core.grammar.json
/usr/include/spirv/1.1/spirv.cs
/usr/include/spirv/1.1/spirv.h
/usr/include/spirv/1.1/spirv.hpp
/usr/include/spirv/1.1/spirv.hpp11
/usr/include/spirv/1.1/spirv.json
/usr/include/spirv/1.1/spirv.lua
/usr/include/spirv/1.1/spirv.py
/usr/include/spirv/1.2/GLSL.std.450.h
/usr/include/spirv/1.2/OpenCL.std.h
/usr/include/spirv/1.2/extinst.glsl.std.450.grammar.json
/usr/include/spirv/1.2/extinst.opencl.std.100.grammar.json
/usr/include/spirv/1.2/spirv.core.grammar.json
/usr/include/spirv/1.2/spirv.cs
/usr/include/spirv/1.2/spirv.h
/usr/include/spirv/1.2/spirv.hpp
/usr/include/spirv/1.2/spirv.hpp11
/usr/include/spirv/1.2/spirv.json
/usr/include/spirv/1.2/spirv.lua
/usr/include/spirv/1.2/spirv.py
/usr/include/spirv/spir-v.xml
/usr/include/spirv/unified1/AMD_gcn_shader.h
/usr/include/spirv/unified1/AMD_shader_ballot.h
/usr/include/spirv/unified1/AMD_shader_explicit_vertex_parameter.h
/usr/include/spirv/unified1/AMD_shader_trinary_minmax.h
/usr/include/spirv/unified1/DebugInfo.h
/usr/include/spirv/unified1/GLSL.std.450.h
/usr/include/spirv/unified1/NonSemanticClspvReflection.h
/usr/include/spirv/unified1/NonSemanticDebugBreak.h
/usr/include/spirv/unified1/NonSemanticDebugPrintf.h
/usr/include/spirv/unified1/NonSemanticShaderDebugInfo100.h
/usr/include/spirv/unified1/OpenCL.std.h
/usr/include/spirv/unified1/OpenCLDebugInfo100.h
/usr/include/spirv/unified1/extinst.debuginfo.grammar.json
/usr/include/spirv/unified1/extinst.glsl.std.450.grammar.json
/usr/include/spirv/unified1/extinst.nonsemantic.clspvreflection.grammar.json
/usr/include/spirv/unified1/extinst.nonsemantic.debugbreak.grammar.json
/usr/include/spirv/unified1/extinst.nonsemantic.debugprintf.grammar.json
/usr/include/spirv/unified1/extinst.nonsemantic.shader.debuginfo.100.grammar.json
/usr/include/spirv/unified1/extinst.opencl.debuginfo.100.grammar.json
/usr/include/spirv/unified1/extinst.opencl.std.100.grammar.json
/usr/include/spirv/unified1/extinst.spv-amd-gcn-shader.grammar.json
/usr/include/spirv/unified1/extinst.spv-amd-shader-ballot.grammar.json
/usr/include/spirv/unified1/extinst.spv-amd-shader-explicit-vertex-parameter.grammar.json
/usr/include/spirv/unified1/extinst.spv-amd-shader-trinary-minmax.grammar.json
/usr/include/spirv/unified1/spirv.bf
/usr/include/spirv/unified1/spirv.core.grammar.json
/usr/include/spirv/unified1/spirv.cs
/usr/include/spirv/unified1/spirv.h
/usr/include/spirv/unified1/spirv.hpp
/usr/include/spirv/unified1/spirv.hpp11
/usr/include/spirv/unified1/spirv.json
/usr/include/spirv/unified1/spirv.lua
/usr/include/spirv/unified1/spirv.py
/usr/include/spirv/unified1/spv.d
/usr/lib64/pkgconfig/SPIRV-Headers.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SPIRV-Headers/9a84200f47e09abfbde1a6b25028460451b23d03
